image:
  - Visual Studio 2015
  - Visual Studio 2017

before_build:
  - set DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ps: Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: ./dotnet-install.ps1 -Channel Current
  - dotnet --info
  - ps: >-
      $env:FSAC_TESTSUITE_MSBUILD_TOOLSVERSION_4_INSTALLED = if ("$env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2017") { "0" } else { "1" };

build_script:
  - cmd: build.cmd All

test: off

artifacts:
  - path: bin\pkgs\*.zip
    name: pkgs
